{
 "title": "rollup_relayer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({service=\"$service\"}, instance)"
    }
   },
   {
    "name": "P99",
    "query": "0.5,0.75,0.95,0.99,0.999,0.9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Chunk Proposer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "propose chunk run rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(rollup_propose_chunk_circle_total{service=\"rollup-relayer\"}[$__rate_interval]))",
       "legendFormat": "run rate"
      }
     ]
    },
    {
     "title": "propose chunk failure rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(rollup_propose_chunk_failure_circle_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "l2 transaction number per chunk",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rollup_propose_chunk_tx_num{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "update proposed chunk info rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(rollup_propose_chunk_update_info_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "calldata size per block",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rollup_l2_block_l1_commit_calldata_size{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "blob size per chunk",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_propose_chunk_total_l1_commit_blob_size{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "calldata size per chunk",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rollup_propose_chunk_total_l1_commit_call_data_size{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "update proposed chunk info failure rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(rollup_propose_chunk_update_info_failure_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "max tx consumption of per chunk",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_propose_chunk_max_tx_consumption{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "block number of per chunk",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rollup_propose_chunk_chunk_block_number{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "chunk block propose not enough rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(rollup_propose_chunk_blocks_propose_not_enough_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "chunk's first block timeout reached rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(rollup_propose_chunk_first_block_timeout_reached_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "${instance}"
      }
     ]
    },
    {
     "title": "commit gas of per chunk (Unit Wei)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_propose_chunk_estimate_l1_commit_gas{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Proposer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "batch proposer run rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "irate(rollup_propose_batch_circle_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch proposer propose failure rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(rollup_propose_batch_failure_circle_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch proposer update info rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "irate(rollup_propose_batch_update_info_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch proposer update info failure rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "irate(rollup_propose_batch_update_info_failure_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "commit gas of per batch (Unit WEI)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rollup_propose_batch_total_l1_commit_gas{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "calldata size of per batch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rollup_propose_batch_total_l1_call_data_size{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "blob size of per batch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rollup_propose_batch_total_l1_commit_blob_size{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "first block timeout reached rate of per batch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "rate(rollup_propose_batch_first_block_timeout_reached_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "chunk number of per batch",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rollup_propose_batch_chunks_number{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "L2 Watcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "fetch running missing blocks height",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rollup_l2_watcher_fetch_running_missing_blocks_height{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    },
    {
     "title": "blocks fetched gap",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rollup_l2_watcher_blocks_fetched_gap{service=\"rollup-relayer\"}",
       "legendFormat": "${instance}-total"
      }
     ]
    }
   ]
  },
  {
   "title": "L2 Relayer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "pending batch handle rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "irate(rollup_layer2_process_pending_batch_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch commit success rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "expr": "irate(rollup_layer2_process_pending_batch_success_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "committed batch handle rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_process_committed_batches_finalized_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "batch finalized success rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 128 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_process_committed_batches_finalized_success_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process committed batches confirmed rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_process_committed_batches_confirmed_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process committed batches confirmed failed rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 137 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_process_committed_batches_confirmed_failed_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process finalized batches confirmed rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_process_finalized_batches_confirmed_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process finalized batches confirmed failed rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 146 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_process_finalized_batches_confirmed_failed_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "call chain monitor failed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_chain_monitor_latest_failed_batch_call{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "L1&L2 status don't match from chain_monitor ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
     "targets": [
      {
       "expr": "rate(rollup_layer2_chain_monitor_latest_failed_batch_status{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "sending transaction rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "irate(rollup_sender_send_transaction_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "re-sending transaction rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 120 },
     "targets": [
      {
       "expr": "irate(rollup_sender_send_transaction_resubmit_send_transaction_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "sender failure",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 131 },
     "targets": [
      {
       "expr": "rollup_sender_send_transaction_full_tx_failure_total{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}-channel-full"
      },
      {
       "expr": "rollup_sender_send_transaction_full_tx_failure_total{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}-repeat-transaction"
      },
      {
       "expr": "rollup_sender_send_transaction_get_fee_failure_total{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}-get-fee-failure"
      },
      {
       "expr": "rollup_sender_send_transaction_send_tx_failure_total{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}-send-tx-failure"
      }
     ]
    },
    {
     "title": "re-sending transaction failure rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 131 },
     "targets": [
      {
       "expr": "irate(rollup_sender_send_transaction_resubmit_send_transaction_failed_total{service=\"rollup-relayer\"}[$__rate_interval])",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "current gas tip cap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 142 },
     "targets": [
      {
       "expr": "rollup_sender_gas_tip_cap{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "current gas fee cap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 142 },
     "targets": [
      {
       "expr": "rollup_sender_gas_fee_cap{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "current blob gas fee cap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 153 },
     "targets": [
      {
       "expr": "rollup_sender_blob_gas_fee_cap{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "current gas limit",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 153 },
     "targets": [
      {
       "expr": "rollup_sender_gas_limit{service=\"rollup-relayer\"}",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    }
   ]
  }
 ]
}