blockscout-stack:
  nameOverride: &app_name "l1-explorer"
  fullnameOverride: *app_name

  blockscout:
    image:
      repository: blockscout/blockscout
      pullPolicy: IfNotPresent
      tag: 6.8.0

    env:
      ETHEREUM_JSONRPC_VARIANT: geth
      BLOCK_TRANSFORMER: clique
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      ECTO_USE_SSL: false
      ETHEREUM_JSONRPC_HTTP_INSECURE: true

    envFrom:
      - configMapRef:
          name: l1-explorer-env

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://l1-explorer.scrollsdk"
        nginx.ingress.kubernetes.io/cors-allow-headers: "updated-gas-oracle, Content-Type, Authorization"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-max-age: "86400"
      hostname: l1-explorer.scrollsdk

  frontend:
    image:
      tag: v1.35.2

    env:
      NEXT_PUBLIC_NETWORK_LOGO: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-logos/scroll.svg"
      NEXT_PUBLIC_NETWORK_LOGO_DARK: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-logos/scroll-dark.svg"
      NEXT_PUBLIC_NETWORK_ICON: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-icons/scroll.svg"
      NEXT_PUBLIC_NETWORK_ICON_DARK: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-icons/scroll-dark.svg"
      NEXT_PUBLIC_HOMEPAGE_HERO_BANNER_CONFIG: "{'background':['rgba(255, 238, 218, 1)'],'text_color':['rgba(25, 6, 2, 1)']}"
      NEXT_PUBLIC_OG_IMAGE_URL: 'https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/og-images/scroll-sepolia.png'
      FAVICON_MASTER_URL: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/favicons/scroll_180x180.png"
      NEXT_PUBLIC_HOMEPAGE_CHARTS: '["daily_txs"]'
      NEXT_PUBLIC_HOMEPAGE_STATS: '["total_blocks", "average_block_time", "total_txs", "wallet_addresses", "gas_tracker"]'
      NEXT_PUBLIC_API_PROTOCOL: http
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
      NEXT_PUBLIC_API_HOST: "l1-explorer.scrollsdk"
      NEXT_PUBLIC_APP_PROTOCOL: http
      NEXT_PUBLIC_AD_BANNER_PROVIDER: none
      NEXT_PUBLIC_AD_TEXT_PROVIDER: none

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://l1-explorer.scrollsdk"
        nginx.ingress.kubernetes.io/cors-allow-headers: "updated-gas-oracle, Content-Type, Authorization"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-max-age: "86400"
      className: "nginx"
      hostname: l1-explorer.scrollsdk
