initContainers:
  1-check-postgres-connection:
    image: atkrad/wait4x:latest
    args:
      - postgresql
      - $(SCROLL_ROLLUP_DB_CONFIG_DSN)
      - --timeout
      - "0"
    envFrom:
      - secretRef:
          name: rollup-node-secret-env
  2-migrate-db:
    image: scrolltech/rollup-db-cli:v4.4.60
    command: ["/bin/sh", "-c", "db_cli migrate --config /config/migrate-db.json"]
    volumeMounts:
      - name: migrate-db
        mountPath: /config/migrate-db.json
        subPath: migrate-db.json
    envFrom:
      - secretRef:
          name: rollup-node-secret-env

resources:
  requests:
    memory: "50Mi"
    cpu: "100m"
  limits:
    memory: "200Mi"
    cpu: "500m"

envFrom:
  - secretRef:
      name: rollup-node-secret-env

persistence:
  migrate-db:
    enabled: true
    type: secret
    mountPath: /config/migrate-db.json
    name: rollup-node-migrate-db
    defaultMode: "0777"

configMaps:
  env:
    enabled: true
    data:
      L1_RPC_ENDPOINT: ""
      L2_RPC_ENDPOINT: ""
      L1_SCROLL_CHAIN_PROXY_ADDR: ""

externalSecrets:
  rollup-node-secret-env:
    provider: aws
    data:
      - remoteRef:
          key: scroll/rollup-node-secret-env
          property: SCROLL_ROLLUP_DB_CONFIG_DSN
        secretKey: SCROLL_ROLLUP_DB_CONFIG_DSN
      - remoteRef:
          key: scroll/rollup-node-secret-env
          property: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_COMMIT_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_COMMIT_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
      - remoteRef:
          key: scroll/rollup-node-secret-env
          property: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_FINALIZE_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_FINALIZE_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
    refreshInterval: 2m
    serviceAccount: external-secrets
  rollup-node-migrate-db:
    provider: aws
    data:
      - remoteRef:
          key: scroll/rollup-node-migrate-db
        secretKey: migrate-db.json
    refreshInterval: 2m
    serviceAccount: external-secrets
