---
global:
  isStandalone: false

image:
  repository: scrolltech/scroll-stack-contracts
  tag: deploy-a976769a2b07ceea7dcd10d0a7a20ad41e010528

envFrom:
  - configMapRef:
      name: contracts-deployment-env

# here is the place for the config.toml file
scrollConfig: |
  {}

# here is the place for the config-contracts.toml file
scrollConfigContracts: |
  {}
