---
apiVersion: v2
description: blockscout scroll helm charts
name: blockscout
version: 0.1.0
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-tech
    email: sebastien@scroll.io
dependencies:
  - name: external-secrets-lib
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 0.0.3
  - name: blockscout-stack
    repository: https://blockscout.github.io/helm-charts
    version: 1.6.8
