blockscout-stack:
  nameOverride: "blockscout"
  fullnameOverride: "blockscout"

  imagePullSecrets:
    - name: docker-secret

  blockscout:
    image:
      repository: blockscout/blockscout-scroll
      pullPolicy: IfNotPresent
      tag: 6.9.0-alpha.1

    env:
      ETHEREUM_JSONRPC_HTTP_URL: http://l2-rpc:8545
      ETHEREUM_JSONRPC_TRACE_URL: http://l2-rpc:8545
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_WS_URL: ws://l2-rpc:8546
      BLOCK_TRANSFORMER: clique
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      CHAIN_TYPE: scroll
      INDEXER_SCROLL_L2_MESSENGER_START_BLOCK: 0
      INDEXER_SCROLL_L1_ETH_GET_LOGS_RANGE_SIZE: 500
      INDEXER_SCROLL_L2_ETH_GET_LOGS_RANGE_SIZE: 500
      SCROLL_L2_CURIE_UPGRADE_BLOCK: 0
      ECTO_USE_SSL: false
      ETHEREUM_JSONRPC_HTTP_INSECURE: true
      # Not sure what these values are for
      #      SCROLL_L1_SCALAR_INIT:
      #      SCROLL_L1_OVERHEAD_INIT:
      #      SCROLL_L1_COMMIT_SCALAR_INIT:
      #      SCROLL_L1_BLOB_SCALAR_INIT:
      #      SCROLL_L1_BASE_FEE_INIT:
      #      SCROLL_L1_BLOB_BASE_FEE_INIT:

    envFrom:
      - configMapRef:
          name: blockscout-env

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://blockscout.scrollsdk"
        nginx.ingress.kubernetes.io/cors-allow-headers: "updated-gas-oracle, Content-Type, Authorization"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-max-age: "86400"
      hostname: blockscout-backend.scrollsdk

  frontend:
    image:
      tag: v1.35.2

    env:
      NEXT_PUBLIC_NETWORK_LOGO: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-logos/scroll.svg"
      NEXT_PUBLIC_NETWORK_LOGO_DARK: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-logos/scroll-dark.svg"
      NEXT_PUBLIC_NETWORK_ICON: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-icons/scroll.svg"
      NEXT_PUBLIC_NETWORK_ICON_DARK: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/network-icons/scroll-dark.svg"
      NEXT_PUBLIC_HOMEPAGE_HERO_BANNER_CONFIG: "{'background':['rgba(255, 238, 218, 1)'],'text_color':['rgba(25, 6, 2, 1)']}"
      NEXT_PUBLIC_OG_IMAGE_URL: 'https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/og-images/scroll-sepolia.png'
      FAVICON_MASTER_URL: "https://raw.githubusercontent.com/blockscout/frontend-configs/main/configs/favicons/scroll_180x180.png"
      NEXT_PUBLIC_HOMEPAGE_CHARTS: '["daily_txs"]'
      NEXT_PUBLIC_HOMEPAGE_STATS: '["total_blocks", "average_block_time", "total_txs", "wallet_addresses", "gas_tracker"]'
      NEXT_PUBLIC_API_PROTOCOL: http
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
      NEXT_PUBLIC_API_HOST: "blockscout-backend.scrollsdk"
      NEXT_PUBLIC_APP_PROTOCOL: http
      NEXT_PUBLIC_AD_BANNER_PROVIDER: none
      NEXT_PUBLIC_AD_TEXT_PROVIDER: none

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://blockscout.scrollsdk"
        nginx.ingress.kubernetes.io/cors-allow-headers: "updated-gas-oracle, Content-Type, Authorization"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-max-age: "86400"
      className: "nginx"
      hostname: blockscout.scrollsdk
