NAMESPACE ?= default

install:
	helm upgrade -i scroll-common scroll-common  -n $(NAMESPACE)
	helm upgrade -i l2-sequencer l2-sequencer -n $(NAMESPACE) --values l2-sequencer/values/production-1.yaml
	helm upgrade -i coordinator-api coordinator-api -n $(NAMESPACE) --values coordinator-api/values/production.yaml
	helm upgrade -i bridge-history-api bridge-history-api -n $(NAMESPACE) --values bridge-history-api/values/production.yaml
	helm upgrade -i bridge-history-fetcher bridge-history-fetcher -n $(NAMESPACE) --values bridge-history-fetcher/values/production.yaml
	helm upgrade -i chain-monitor chain-monitor -n $(NAMESPACE) --values chain-monitor/values/production.yaml
	helm upgrade -i coordinator-cron coordinator-cron -n $(NAMESPACE) --values coordinator-cron/values/production.yaml
	helm upgrade -i frontends frontends -n $(NAMESPACE) --values frontends/values/production.yaml
	helm upgrade -i gas-oracle gas-oracle -n $(NAMESPACE) --values gas-oracle/values/production.yaml
	helm upgrade -i l2-bootnode l2-bootnode -n $(NAMESPACE) --values l2-bootnode/values/production-1.yaml
	helm upgrade -i l2-rpc l2-rpc -n $(NAMESPACE) --values l2-rpc/values/production.yaml
	helm upgrade -i rollup-explorer-backend rollup-explorer-backend -n $(NAMESPACE) --values rollup-explorer-backend/values/production.yaml
	helm upgrade -i rollup-node rollup-node -n $(NAMESPACE) --values rollup-node/values/production.yaml
	helm upgrade -i contracts contracts -n $(NAMESPACE) --values contracts/values/production.yaml

delete:
	helm delete -n $(NAMESPACE) scroll-common
	helm delete -n $(NAMESPACE) l2-sequencer
	helm delete -n $(NAMESPACE) coordinator-api
	helm delete -n $(NAMESPACE) bridge-history-api
	helm delete -n $(NAMESPACE) bridge-history-fetcher
	helm delete -n $(NAMESPACE) chain-monitor
	helm delete -n $(NAMESPACE) coordinator-cron
	helm delete -n $(NAMESPACE) frontends
	helm delete -n $(NAMESPACE) gas-oracle
	helm delete -n $(NAMESPACE) l2-bootnode
	helm delete -n $(NAMESPACE) l2-rpc
	helm delete -n $(NAMESPACE) rollup-explorer-backend
	helm delete -n $(NAMESPACE) rollup-node
	helm delete -n $(NAMESPACE) contracts
